# Use an official Python runtime as the base image
FROM python:3.8-alpine

# Set the working directory
WORKDIR /app

# Copy the application code to the working directory
COPY . /app

# Install the required packages
RUN apk add --no-cache --virtual .build-deps \
    build-base \
    libffi-dev \
    openssl-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del .build-deps

# Expose port 5000 for the Flask application to listen on
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]
